# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1_text', models.CharField(max_length=200)),
                ('option2_text', models.CharField(max_length=200)),
            ],
        ),
    ]
