# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='theme',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
