# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rather', '0004_option_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='id',
        ),
        migrations.AlterField(
            model_name='option',
            name='theme',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
