# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagelink',
            field=models.CharField(max_length=200),
        ),
    ]
