# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0002_auto_20170521_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.IntegerField(default=2701),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='imagelink',
            field=models.URLField(),
        ),
    ]
