# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0003_auto_20170527_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='camera',
        ),
    ]
